export const currencies = [
	'PLN',
	'EUR',
	'USD',
	'GBP',
	'CHF',
    'JPY',
    'CNY',
    'CAD',
    'AUD',
    'NZD',
    'HKD',
    'SGD',
    'MYR',
    'RUB',
    'DKK',
    'NOK',
    'SEK',
    'ISK',
    'HRK',
    'CZK',
    'HUF',
    'RON',
    'BGN',
    'MXN',
    'BRL',
    'PHP',
    'INR',
    'IDR',
	'THB',
	'ZAR',
	'ILS'
];

export const currenciesNames = [
    "Polish zloty (PLN)",
    "Euro (EUR)",
    "United States dollar (USD)",
    "Pound sterling (GBP)",
    "Swiss franc (CHF)",
    "Japanese yen (JPY)",
    "Chinese yuan (CNY)",
    "Canadian dollar (CAD)",
    "Australian dollar (AUD)",
    "New Zealand dollar (NZD)",
    "Hong Kong dollar (HKD)",
    "Singapore dollar (SGD)",
    "Malaysian ringgit (MYR)",
    "Russian ruble (RUB)",
    "Danish krone (DKK)",
    "Norwegian krone (NOK)",
    "Swedish krona (SEK)",
    "Icelandic krona (ISK)",
    "Croatian kuna (HRK)",
    "Czech koruna (CZK)",
    "Hungarian forint (HUF)",
    "Romanian leu (RON)",
    "Bulgarian lev (BGN)",
    "Mexican peso (MXN)",
    "Brazilian real (BRL)",
    "Philippine peso (PHP)",
    "Indian rupee (INR)",
    "Indonesian rupiah (IDR)",
    "Thai baht (THB)",
    "South African rand (ZAR)",
    "Israeli new shekel (ILS)"
];